# The first time I heard anything about GitHub Actions was at Section 7: Continuous Integration and Deployment with AWS. 86: GitHub Actions Instead of Travis CI
name: Deploy MultiDocker
on:
  push:
    branches:
      - master # check your repo, your default branch might be master!

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
  # Log in to the docker CLI
      - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - run: docker build -t react-test -f ./client/Dockerfile.dev ./client
      - run: docker run -e CI=true  react-test npm test

  # Reminder, the ./client tells docker where to look for the Dockerfile since we are not in that folder here, we are in .github/workflows here
  # April 4 I am noticing that these are building using the production Dockerfile and not the Dockerfile.dev. Those make for more compact image sizes.
      - run: docker build -t cjmarek/multi-client ./client
      - run: docker build -t cjmarek/multi-nginx ./nginx
      - run: docker build -t cjmarek/multi-server ./server
      - run: docker build -t cjmarek/multi-worker ./worker
  # Take those images and push them to docker hub
      - run: docker push cjmarek/multi-client
      - run: docker push cjmarek/multi-nginx
      - run: docker push cjmarek/multi-server
      - run: docker push cjmarek/multi-worker

      #  This stuff (line 35 down) is for deploying to AWS. I found this shit by clicking a link I
      #  found at at Section 7: Continuous Integration and Deployment with AWS. 86: GitHub Actions Instead of Travis CI . . . .
      # https://www.udemy.com/course/docker-and-kubernetes-the-complete-guide/learn/lecture/11437142#questions/17673926
      #  After you go to the link, you have to scroll down! to find this information.
      
      # - name: Generate deployment package
      #   run: zip -r deploy.zip . -x '*.git*'

      # - name: Deploy to EB
      #   uses: einaregilsson/beanstalk-deploy@v18
      #   with:
      #     aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
      #     aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
      #     application_name: multi-gh
      #     environment_name: Multigh-env
      #     existing_bucket_name: elasticbeanstalk-us-east-1-923445559289  
      #     region: us-east-1
      #     version_label: ${{ github.sha }}
      #     deployment_package: deploy.zip

